config/routes.rb
Rails.application.routes.draw do
  get 'contact_us/contact'

  get 'home/index'

  get 'app/assets/views/orders/index.html.erb', to: "users#admin_check"
  
  resources :orders
  devise_for :users
  resources :users
  
  root 'home#index'
  
  

end

app/models/order.rb
class Order < ActiveRecord::Base
     belongs_to :user
     has_and_belongs_to_many:users
     #validates :user_id, presence: true
     before_save do
        self.toppings.gsub!(/[\[\]\"]/, "") if attribute_present?('toppings')
    end
    
    before_save do
        self.status.gsub!(/[\[\]\"]/, "") if attribute_present?('status')
    end
    
    validates :address, presence:true
    
    validates :city, presence: true
    
    phonenumber_validation =  /\d{3}-\d{3}-\d{4}/
      validates :phonenumber, :presence => true, :format => { :with => phonenumber_validation , message: " - please use this format 123-234-3456"  }
      
    zip_canada = /\A[a-zA-Z]{1}\d{1}[a-zA-Z]{1}[ -]?\d{1}[a-zA-Z]{1}\d{1}\z/
    validates :postalcode, :presence => true, :format => { :with => zip_canada }
    
    validates :size, presence:true
    
    validates :crust, presence:true
    
    validates :toppings, presence:true
    
    def price
          @sizeprice = 0;
          @crustprice = 0;
          @toppingprice = 0;
          @numberofpizzaprice=0;
          @tax = 0;
          @totalprice = 0;
          @grandtotal=0;
          
          if self.province=='ON'
                 @tax=0.13
            elsif self.province=='MB'
                 @tax=0.10
            elsif self.province=='SK'
                 @tax=0.15
            elsif self.province=='QC'
                 @tax=0.11
          end
          
          if self.size=='small'
               @sizeprice=5.00
          elsif self.size=='medium'
               @sizeprice=10.00
          elsif self.size=='large'
               @sizeprice=15.00
          elsif self.size=='xlarge'
               @sizeprice=20.00
          end
               
          
           if self.crust == "Stuff_Crust"
               @CrustPrice =  2.0;
           end
          
            
            if attribute_present?("toppings")
                 @toppingprice=self.toppings.count(',')*0.5
            end
            
            @totalprice = @sizeprice + @crustprice + @toppingprice + @tax;
                
                if attribute_present?("numberofpizza")
                 @totalprice=@totalprice*self.numberofpizza;
                end    
            
            @grandtotal= (@totalprice + (@tax * @totalprice));
            return @grandtotal
    end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def contact
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]
 

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    
    @order = current_user.orders.new(order_params)
    
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :province, :postalcode, :phonenumber, :size, :crust, {:toppings => []}, :numberofpizza, :price,:status,:user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :set_user, only:[:show, :edit, :update, :destroy]

  
  # GET /users
  # GET /users.json
  
  def index
    @users=User.all
  end
    
  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: '' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: '' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
    
    def checked(area)
        @order.toppings.nil? ? false : @order.toppings.match(area)
    end
    
    #def checked(area)
     #   @order.status.nil? ? false : @order.status.match(area)
    #end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact_us/contact.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" method="post">
                    <fieldset>
                        <legend class="text-center header">Contact us</legend>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="fname" name="name" type="text" placeholder="First Name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="lname" name="name" type="text" placeholder="Last Name" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-envelope-o bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="email" name="email" type="text" placeholder="Email Address" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-phone-square bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="phone" name="phone" type="text" placeholder="Phone" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-pencil-square-o bigicon"></i></span>
                            <div class="col-md-8">
                                <textarea class="form-control" id="message" name="message" placeholder="Enter your massage for us here. We will get back to you within 2 business days." rows="7"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<h1></h1>
<p></p>

app/views/layouts/_home.html.erb
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>
        Conestoga Pizzeria
        </title>
        
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" 
              integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
        
        <!--<link rel="stylesheet" type="text/css" href="stylesheet/main.css">-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <!--<script src="Scripts/myscript.js"></script> -->
        
        
     </head>
    <body>
        <div class="container">
            <div class="navbar navbar-default navbar-fixed">
                <div class="container">
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                   <!-- <img src="images/clogo.png" alt="conestoga" height="50px" width="35px">-->
                    </div>
                    <div class="collapse navbar-collapse" id="example">
                        <ul class="nav navbar-nav">
                            <li><a><span class="glyphicon glyphicon-home"></span>Home</a></li>
                            <li><%=
                            if(user_signed_in? && !current_user.admin?)
                                link_to "Order", new_order_path(@order), :class=>"glyphicon glyphicon-shopping-cart"
                            elsif
                                link_to "Order", new_order_path(@order), :class=>"glyphicon glyphicon-shopping-cart"
                            end%></li>
                            <li><a><span class="glyphicon glyphicon-heart-empty"></span>About us</a></li>
                            <li><%= link_to "Contact Us", contact_us_contact_path %></li>
                        </ul>
                        
                        <% if !user_signed_in? %> 
                            <a class="btn btn-success navbar-btn navbar-right" <%= link_to"Login", new_user_session_path(@user) %> </a>
                        <% end %>
                        
                        <% if user_signed_in? %>
                            
                               <a class="btn btn-danger navbar-btn navbar-right"<%= link_to('Logout', destroy_user_session_path, :method => :delete) %></a>
                                  <% #if current_user.admin?%>
                                  <%# render :file => "orders/index.html.erb" %>
                                  <%#end%>
                        <% end %>
                          
                    </div>
                </div>
            </div>
            
            <div class="container">
                <div class="jumbotron">
                    <div class="container">
                        <div class="col-md-8">
                            <h1>Conestoga Pizzeria</h1>
                            <h3>Good Friends. Great Pizza.</h3>
                            
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="container">
                <% if user_signed_in? %>
                <h2> Hi  <mark>  <%= current_user.name %> </mark>, Welcome to Conestoga Pizzeria </h2>
                <% end %>
                
                
                <%= if (user_signed_in? && current_user.admin?)
                      link_to 'Show Orders', orders_path, :class => 'btn btn-success'
                    end %>
         
                <%= if (user_signed_in? && current_user.admin?)
                      link_to 'Show Users', users_path, :class => 'btn btn-success'
                    end %>
                    
                <%= if (user_signed_in? && current_user.admin?)
                      link_to 'Add User', new_user_path, :class => 'btn btn-success'
                    end %> 
            </div>
            
        </div>    
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
      <%= render :file => 'layouts/_home.html.erb' %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
  <div class="alert alert-danger">
    
  
    <div id="error_explanation">
      <h3><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h3>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    </div>
  <% end %>
  <div class="container">
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel panel-heading">
          <span class="glyphicon glyphicon-map-marker"></span> Address Information
        </div>
        <div class="field">
          <%= f.label :address %><br>
          <%= f.text_field :address, :class => "form-control" %>
        </div>
        <div class="field">
          <%= f.label :city %><br>
          <%= f.text_field :city, :class => "form-control" %>
        </div>
        <div class="field">
          <%= f.label :province %><br>
          <%= f.select(:province, options_for_select([['ON', 'ON'] , ['MB' , 'MB'], ['SK','SK' ], ['QC', 'QC'] ] ),{},{:class => "form-control"}) %>
        </div>
        <div class="field">
          <%= f.label :postalcode %><br>
          <%= f.text_field :postalcode, :class => "form-control" %>
        </div>
        <div class="field">
          <%= f.label :phonenumber %><br>
          <%= f.text_field :phonenumber, :class => "form-control" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel panel-heading">
          <span class="glyphicon glyphicon-info-sign"></span> Information
        </div>
        <div>
          <ul>
            <li id="instruction">Price will be According to Your selected Size, Crust and Toppings.</li>
            <li id="instruction">Small Size - $5</li>
            <li id="instruction">Medium Size - $10</li>
            <li id="instruction">Large Size - $15</li>
            <li id="instruction">X-Large - $20 </li>
            <li id="instruction">Stuff Crust - $2 extra</li>
            <li id="instruction">Each Toppings will cost you $0.5 More.</li>
            <li id="instruction">First Topping will be free.</li>
            <li id="instruction">You can select your favourite Sauce.</li>
            <li id="instruction">Please select Current Option, So, You can see next option.</li>
          </ul>
        </div>
      </div> 
    </div>
  </div>
  <div class="container">
    <div class="col-md-3">
      <div class="panel panel-primary">
        <div class="panel panel-heading">
          <span class="glyphicon glyphicon-hand-down"></span> Select Size:
        </div>  
        <div class="form-group">
          <div class="field">
            <%= f.label :size  %><br>
            <%= f.radio_button :size, 'small', :id => 'field_with_error' %>
            <%= label_tag(:small,"small") %><br>
            <%= f.radio_button :size, 'medium', :id => 'field_with_error'  %>
            <%= label_tag(:medium,"medium") %><br>
            <%= f.radio_button :size, 'large', :id => 'field_with_error'  %>
            <%= label_tag(:large,"large") %><br>
            <%= f.radio_button :size, 'xlarge', :id => 'field_with_error'  %>
            <%= label_tag(:xlarge,"xlarge") %><br>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="panel panel-primary">
        <div class="panel panel-heading">
          <span class="glyphicon glyphicon-hand-down"></span> Select Pizza Crust:
        </div> 
        <div class="field">
          <%= f.label :crust %><br>
          <%= f.radio_button :crust, 'Regular' %> Regular<br />
          <%= f.radio_button :crust, 'Stuff_Crust' %> Stuff Crust<br />
          <%= f.radio_button :crust, 'Crunchy_Thin' %> Crunchy Thin<br />
          <%= f.radio_button :crust, 'Thick' %> Thick<br />
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="panel panel-primary">
        <div class="panel panel-heading">
          <span class="glyphicon glyphicon-hand-down"></span> Select Toppings:
        </div>  
        <div class="field">
          <%= f.label :toppings %><br>
          <%= check_box_tag 'order[toppings][]', 'Onion', checked('Onion'), id:'orders_toppings' %> 
          <%= label_tag 'orders_toppings', 'Onion' %><br>
          
          <%= check_box_tag 'order[toppings][]', 'GreenPepper', checked('GreenPepper'), id:'orders_toppings' %>
          <%= label_tag 'orders_toppings', 'GreenPepper' %><br>
          
          <%= check_box_tag 'order[toppings][]', 'Pineapple', checked('Pineapple'), id:'orders_toppings' %>
          <%= label_tag 'orders_toppings', 'Pineapple' %><br>
          
          <%= check_box_tag 'order[toppings][]', 'Mashroom', checked('Mashroom'), id:'orders_toppings' %>
          <%= label_tag 'orders_toppings', 'Mashroom' %><br>
          
          <%= check_box_tag 'order[toppings][]', 'Tomato', checked('Tomato'), id:'orders_toppings' %>
          <%= label_tag 'orders_toppings', 'Tomato' %><br>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="panel panel-primary">
        <div class="panel panel-heading">
          <span class="glyphicon glyphicon-hand-down"></span> Select Toppings:
        </div>
        <div class="field">
          <%= f.label :toppings %><br>
          <%= check_box_tag 'order[toppings][]', 'GreenOlives', checked('GreenOlives'), id:'orders_toppings' %>
          <%= label_tag 'orders_toppings', 'GreenOlives' %><br>
          
          <%= check_box_tag 'order[toppings][]', 'BlackOlives', checked('BlackOlives'), id:'orders_toppings' %>
          <%= label_tag 'orders_toppings', 'BlackOlives' %><br>
          
          <%= check_box_tag 'order[toppings][]', 'Chicken', checked('Chicken'), id:'orders_toppings' %>
          <%= label_tag 'orders_toppings', 'Chicken' %><br>
          
          <%= check_box_tag 'order[toppings][]', 'Bacon', checked('Bacon'), id:'orders_toppings' %>
          <%= label_tag 'orders_toppings', 'Bacon' %><br>
          
          <%= check_box_tag 'order[toppings][]', 'Ham', checked('Ham'), id:'orders_toppings' %>
          <%= label_tag 'orders_toppings', 'Ham' %><br>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="col-md-6">
      <div class="field">
        <%= f.label :numberofpizza %><br>
        <%= f.number_field :numberofpizza, :class => "form-control"  %>
      </div>
    </div>
      
      
    
      <div class="col-md-6">
      <div class="actions">
        <%= f.submit:order, :class=> "btn btn-success" %>
      </div>
    </div>
  </div>
 <% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<div class="table-striped">          
  <table class="table">
  <thead>
    <tr>
      <th>Order No.</th>
      <th>Address</th>
      <th>City</th>
      <th>Province</th>
      <th>Postalcode</th>
      <th>Phonenumber</th>
      <th>Size</th>
      <th>Crust</th>
      <th>Toppings</th>
      <th>Numberofpizza</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
   <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.province %></td>
        <td><%= order.postalcode %></td>
        <td><%= order.phonenumber %></td>
        <td><%= order.size %></td>
        <td><%= order.crust %></td>
        <td><%= order.toppings %></td>
        <td><%= order.numberofpizza %></td>
        <td><%= order.price %></td>
       
        <td>
           <%= if (user_signed_in? && current_user.admin?)
              label_tag(:status,"status")
              select_tag "status","<option>UnComplete</option><option>Complete</option>".html_safe
            end %>
          
          
        </td>
        
        <td><a class="btn btn-success"<%= link_to 'Show', order %></a></td>
        <td><a class="btn btn-primary"<%= link_to 'Edit', edit_order_path(order) %></a></td>
        <td><%= link_to '', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to '', new_order_path %>

app/views/orders/new.html.erb
<%= render 'form' %>
<div class="container">
    <%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="container">
    <div class="content">
    
    <div class="col-md-12">
      <div class="panel panel-success">
      <div class="panel-heading"> Your Order Summary </div>
      <div class="panel-body">
        
        <p>
          <strong>Address:</strong>
          <%= @order.address %>
        </p>
        
        <p>
          <strong>City:</strong>
          <%= @order.city %>
        </p>
        
        <p>
          <strong>Province:</strong>
          <%= @order.province %>
        </p>
        
        <p>
          <strong>Postalcode:</strong>
          <%= @order.postalcode %>
        </p>
        
        <p>
          <strong>Phonenumber:</strong>
          <%= @order.phonenumber %>
        </p>
        
        <p>
          <strong>Size:</strong>
          <%= @order.size %>
        </p>
        
        <p>
          <strong>Crust:</strong>
          <%= @order.crust %>
        </p>
        
        <p>
          <strong>Toppings:</strong>
          <%= @order.toppings %>
        </p>
        
        <p>
          <strong>Numberofpizza:</strong>
          <%= @order.numberofpizza %>
        </p>
        
        <p>
          <strong>Price:</strong>
          <%= @order.price %>
        </p>
        
        <p>
          <strong>id:</strong>
          <%= current_user.id %>
        </p>
  
        <a class="btn btn-success navbar-btn" <%= link_to 'Edit', edit_order_path(@order) %> </a>
       
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
   <%-# f.hidden_field: user_id -%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="col-md-12">
      <h1>Listing Users</h1>
  </div>
  <div class="col-md-12">
  <div class="table-striped">          
  <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <% if (user_signed_in? && current_user.admin?)%>
                    <th>Admin</th>
          <%end %>
          
          <th colspan="3"></th>
        </tr>
      </thead>
    
    <tbody>
     
     <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= if (user_signed_in? && current_user.admin?)
                    user.admin
                    end %></td>
        
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
     <%end%>
    </tbody>
  </table>
  </div>
  </div>
  
<br>

<%= link_to '', new_user_path %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>